name = "day05"
description = "Advent Of Code 2025 with Ada - day 05"
version = "0.1.0-dev"

authors = ["Simon Bean"]
maintainers = ["Simon Bean <smionean@gmail.com>"]
maintainers-logins = ["smionean"]
licenses = "MIT"
website = "https://github.com/smionean/AdventOfCode"
tags = []

executables = ["day05"]

[build-switches]
"*".ada_version = "Ada2022"
